site_name: Monokle
site_description: 'Your K8s best friend'
site_author: 'Kubeshop Monokle Team'
docs_dir: docs/
repo_name: 'kubeshop/monokle'
repo_url: 'https://github.com/kubeshop/monokle'
edit_uri: blob/main/docs/

theme:
  name: material
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml

nav:
  - Welcome: index.md
  - Feature Overview: features.md
  - Getting Started: getting-started.md
  - UI Overview: overview.md
  - Navigating Resources: resource-navigation.md
  - Resource Editing: resource-editing.md
  - Working with Kustomize: kustomize.md
  - Working with Helm Charts: helm.md
  - Cluster Integration: cluster-integration.md
  - Apply/Diff: apply-and-diff.md
  - Architecture: architecture.md
  - Tutorials:
    - tutorials/how-to-navigate-k8s-resources-and-their-the-manifests.md
    - tutorials/how-to-browse-clusters.md
    - tutorials/configuring-monokle.md

extra:
  analytics:
    provider: google
    property: UA-204665550-5

  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: Copyright &copy; 2021 <a href="https://kubeshop.io">Kubeshop</a>

