site_name: Monokle
site_description: 'Your K8s best friend'
site_author: 'Kubeshop Monokle Team'
docs_dir: docs/
repo_name: 'kubeshop/monokle'
repo_url: 'https://github.com/kubeshop/monokle'
edit_uri: blob/main/docs/

theme:
  name: material
  locale: en
  highlightjs: true
  analytics:
    gtag: G-ZDGQ7HPJSC
  hljs_languages:
    - yaml

nav:
  - Welcome: index.md
  - Getting Started: getting-started.md
  - Features: features.md
  - UI Overview: overview.md
  - Navigating Resources: resource-navigation.md
  - Resource Editing: resource-editing.md
  - Working with Kustomize: kustomize.md
  - Working with Helm Charts: helm.md
  - Cluster Preview: cluster-preview.md
  - Apply/Diff: apply-and-diff.md
  - Architecture: architecture.md

copyright: Copyright &copy; 2021 <a href="https://kubeshop.io">Kubeshop</a>

